const erroresStripe = {
    account_already_exists: 'La dirección de correo electrónico proporcionada para la creación de una cuenta diferida ya tiene una cuenta asociada. Utilice el flujo de OAuth para conectar la cuenta existente a su plataforma.',
    account_country_invalid_address: 'El país de la dirección comercial proporcionada no coincide con el país de la cuenta. Las empresas deben estar ubicadas en el mismo país que la cuenta.',
    account_invalid: 'El ID de cuenta proporcionado como valor para el encabezado Stripe-Account no es válido. Verifique que sus solicitudes especifiquen una identificación de cuenta válida.',
    account_number_invalid: 'El número de cuenta bancaria proporcionado no es válido (por ejemplo, faltan dígitos). La información de la cuenta bancaria varía de un país a otro. Recomendamos crear validaciones en sus formularios de inscripción en función de los formatos de cuenta bancaria que proporcionamos.',
    acss_debit_session_incomplete: 'La sesión de débito de ACSS aún no está lista para pasar al estado completo. Vuelva a intentar la solicitud más tarde.',
    alipay_upgrade_required: 'Este método para crear pagos de Alipay ya no es compatible. Actualice su integración para utilizar Fuentes en su lugar.',
    amount_too_large: 'La cantidad especificada es mayor que la cantidad máxima permitida. Use una cantidad menor y vuelva a intentarlo.',
    amount_too_small: 'La cantidad especificada es menor que la cantidad mínima permitida. Use una cantidad mayor y vuelva a intentarlo.',
    api_key_expired: 'La clave de API proporcionada ha caducado. Obtenga sus claves API actuales del Panel y actualice su integración para usarlas.',
    authentication_required: 'El pago requiere autenticación para continuar. Si su cliente está fuera de sesión, notifique a su cliente que regrese a su aplicación y complete el pago. Si proporcionó el parámetro error_on_requires_action, su cliente debe probar con otra tarjeta que no requiera autenticación.',
    balance_insufficient: 'La transferencia o el pago no se pudo completar porque la cuenta asociada no tiene suficiente saldo disponible. Cree una nueva transferencia o pago utilizando una cantidad menor o igual al saldo disponible de la cuenta.',
    bank_account_declined: 'La cuenta bancaria proporcionada no se puede utilizar para realizar cargos, ya sea porque aún no está verificada o porque no es compatible.',
    bank_account_exists: 'La cuenta bancaria proporcionada ya existe en el objeto Cliente especificado. Si la cuenta bancaria también debe adjuntarse a un cliente diferente, incluya el ID de cliente correcto cuando vuelva a realizar la solicitud.',
    bank_account_unusable: 'La cuenta bancaria proporcionada no se puede utilizar para pagos. Se debe utilizar una cuenta bancaria diferente.',
    bank_account_unverified: 'Su plataforma Connect está intentando compartir una cuenta bancaria no verificada con una cuenta conectada.',
    bank_account_verification_failed: 'La cuenta bancaria no se puede verificar, ya sea porque los montos del microdepósito proporcionados no coinciden con los montos reales o porque la verificación ha fallado demasiadas veces.',
    billing_invalid_mandate: 'La Suscripción o Factura intentó pagar en un Método de Pago sin un mandato activo. Para crear pagos de Suscripción o Factura con este Método de Pago, primero debe confirmarse en la sesión con un PaymentIntent o SetupIntent.',
    bitcoin_upgrade_required: 'Este método para crear pagos con Bitcoin ya no es compatible. Actualice su integración para utilizar Fuentes en su lugar.',
    card_decline_rate_limit_exceeded: 'Esta tarjeta ha sido rechazada demasiadas veces. Puede intentar cargar esta tarjeta nuevamente después de 24 horas. Le sugerimos que se comunique con su cliente para asegurarse de que haya ingresado toda su información correctamente y de que no haya problemas con su tarjeta.',
    card_declined: 'La tarjeta ha sido rechazada. Cuando se rechaza una tarjeta, el error devuelto también incluye el atributo declive_code con el motivo por el cual se rechazó la tarjeta. Consulte nuestra documentación de códigos de rechazo para obtener más información.',
    charge_already_captured: 'El cargo que estás intentando capturar ya ha sido capturado. Actualice la solicitud con un ID de cargo no capturado.',
    charge_already_refunded: 'El cargo que está intentando reembolsar ya se reembolsó. Actualice la solicitud para usar el ID de un cargo que no ha sido reembolsado.',
    charge_disputed: 'El cargo que está intentando reembolsar se ha devuelto. Consulte la documentación de disputas para saber cómo responder a la disputa.',
    charge_exceeds_source_limit: 'Este cargo haría que exceda el límite de procesamiento de la ventana móvil para este tipo de fuente. Vuelva a intentar el cargo más tarde o comuníquese con nosotros para solicitar un límite de procesamiento más alto.',
    charge_expired_for_capture: 'El cargo no se puede capturar porque la autorización ha expirado. Los cargos de autenticación y captura deben capturarse en un plazo de siete días.',
    charge_invalid_parameter: 'Uno o más parámetros proporcionados no se permitieron para la operación dada en el Cargo. Consulte nuestra referencia de API o el mensaje de error devuelto para ver qué valores no eran correctos para ese cargo.',
    clearing_code_unsupported: 'El código de compensación proporcionado no es compatible.',
    country_code_invalid: 'El código de país proporcionado no es válido.',
    country_unsupported: 'Su plataforma intentó crear una cuenta personalizada en un país que aún no es compatible. Asegúrese de que los usuarios solo puedan registrarse en países admitidos por cuentas personalizadas.',
    coupon_expired: 'El cupón proporcionado para una suscripción o un pedido ha caducado. Cree un nuevo cupón o use uno existente que sea válido.',
    customer_max_payment_methods: 'Se ha alcanzado el número máximo de métodos de pago para este cliente. Separe algunos métodos de pago de este cliente o proceda con un cliente diferente.',
    customer_max_subscriptions: 'Se alcanzó el número máximo de suscripciones para un cliente. Contáctenos si recibe este error.',
    email_invalid: 'La dirección de correo electrónico no es válida (por ejemplo, no está formateada correctamente). Compruebe que la dirección de correo electrónico esté formateada correctamente y solo incluya los caracteres permitidos.',
    expired_card: 'La tarjeta ha caducado. Verifique la fecha de vencimiento o use una tarjeta diferente.',
    idempotency_key_in_use: 'La clave de idempotencia proporcionada se está utilizando actualmente en otra solicitud. Esto ocurre si su integración realiza solicitudes duplicadas simultáneamente.',
    incorrect_address: 'La dirección de la tarjeta es incorrecta. Verifique la dirección de la tarjeta o use una tarjeta diferente.',
    incorrect_cvc: 'El código de seguridad de la tarjeta es incorrecto. Verifique el código de seguridad de la tarjeta o use una tarjeta diferente.',
    incorrect_number: 'El número de tarjeta es incorrecto. Verifique el número de la tarjeta o use una tarjeta diferente.',
    incorrect_zip: 'El código postal de la tarjeta es incorrecto. Verifique el código postal de la tarjeta o use una tarjeta diferente.',
    instant_payouts_unsupported: 'Esta tarjeta no es elegible para pagos instantáneos. Pruebe con una tarjeta de débito de un banco admitido.',
    intent_invalid_state: 'La intención no está en el estado requerido para realizar la operación.',
    intent_verification_method_missing: 'La intención no tiene un método de verificación especificado en su objeto PaymentMethodOptions.',
    invalid_card_type: 'La tarjeta proporcionada como una cuenta externa no es compatible con los pagos. En su lugar, proporcione una tarjeta de débito que no sea de prepago.',
    invalid_characters: 'Este valor proporcionado al campo contiene caracteres que no son compatibles con el campo.',
    invalid_charge_amount: 'La cantidad especificada no es válida. El monto del cargo debe ser un número entero positivo en la unidad monetaria más pequeña y no debe exceder el monto mínimo o máximo.',
    invalid_cvc: 'El código de seguridad de la tarjeta no es válido. Verifique el código de seguridad de la tarjeta o use una tarjeta diferente.',
    invalid_expiry_month: 'El mes de vencimiento de la tarjeta es incorrecto. Verifique la fecha de vencimiento o use una tarjeta diferente.',
    invalid_expiry_year: 'El año de vencimiento de la tarjeta es incorrecto. Verifique la fecha de vencimiento o use una tarjeta diferente.',
    invalid_number: 'El número de tarjeta no es válido. Verifique los detalles de la tarjeta o use una tarjeta diferente.',
    invalid_source_usage: 'La fuente no se puede usar porque no está en el estado correcto (por ejemplo, una solicitud de cargo está intentando usar una fuente con una fuente pendiente, fallida o consumida). Verifique el estado de la fuente que está intentando utilizar.',
    invoice_no_customer_line_items: 'No se puede generar una factura para el cliente especificado ya que no hay elementos de factura pendientes. Verifique que se esté especificando el cliente correcto o cree primero los artículos de factura necesarios.',
    invoice_no_payment_method_types: 'No se puede finalizar una factura porque no hay tipos de métodos de pago disponibles para procesar el pago. Es posible que la configuración de su plantilla de factura o la configuración de pago de la factura estén restringiendo qué métodos de pago están disponibles, o es posible que deba activar más métodos de pago en el Panel de control.',
    invoice_no_subscription_line_items: 'No se puede generar una factura para la suscripción especificada ya que no hay elementos de factura pendientes. Verifique que se especifique la suscripción correcta o cree primero los elementos de factura necesarios.',
    invoice_not_editable: 'La factura especificada ya no se puede editar. En su lugar, considere la posibilidad de crear elementos de factura adicionales que se aplicarán a la próxima factura. Puede generar manualmente la siguiente factura o esperar a que se genere automáticamente al final del ciclo de facturación.',
    invoice_payment_intent_requires_action: 'Este pago requiere una acción adicional del usuario antes de que se pueda completar con éxito. El pago se puede completar utilizando el PaymentIntent asociado con la factura. Mira esta pagina para mas detalles.',
    invoice_upcoming_none: 'No hay una próxima factura del cliente especificado para obtener una vista previa. Solo los clientes con suscripciones activas o elementos de factura pendientes tienen facturas que se pueden previsualizar.',
    livemode_mismatch: 'Las claves, las solicitudes y los objetos de la API del modo de prueba y en vivo solo están disponibles en el modo en el que se encuentran.',
    lock_timeout: 'No se puede acceder a este objeto en este momento porque otra solicitud de API o proceso de Stripe está accediendo actualmente. Si ve este error de forma intermitente, vuelva a intentar la solicitud. Si ve este error con frecuencia y está realizando varias solicitudes simultáneas a un solo objeto, haga sus solicitudes en serie o a un ritmo menor. Consulte la documentación del límite de tarifa para obtener más detalles.',
    missing: 'Se han proporcionado tanto un ID de cliente como de fuente, pero la fuente no se ha guardado para el cliente. Para crear un cargo para un cliente con una fuente específica, primero debe guardar los detalles de la tarjeta.',
    not_allowed_on_standard_account: 'No se permiten transferencias ni pagos en nombre de una cuenta conectada estándar.',
    order_creation_failed: 'No se pudo crear el pedido. Verifique los detalles del pedido y vuelva a intentarlo.',
    order_required_settings: 'No se pudo procesar el pedido porque falta la información requerida. Verifique la información proporcionada y vuelva a intentarlo.',
    order_status_invalid: 'El pedido no se puede actualizar porque el estado proporcionado no es válido o no sigue el ciclo de vida del pedido (p. Ej., Un pedido no puede pasar de creado a completado sin primero pasar a pago).',
    order_upstream_timeout: 'La petición caducó. Inténtelo de nuevo más tarde.',
    out_of_inventory: 'El SKU está agotado. Si hay más existencias disponibles, actualice la cantidad de inventario de SKU y vuelva a intentarlo.',
    parameter_invalid_empty: 'No se proporcionaron uno o más valores obligatorios. Asegúrese de que las solicitudes incluyan todos los parámetros obligatorios.',
    parameter_invalid_integer: 'Uno o más de los parámetros requieren un número entero, pero los valores proporcionados eran de un tipo diferente. Asegúrese de que solo se proporcionen valores admitidos para cada atributo. Consulte nuestra documentación de API para buscar el tipo de datos que admite cada atributo.',
    parameter_invalid_string_blank: 'Uno o más valores proporcionados solo incluían espacios en blanco. Verifique los valores en su solicitud y actualice los que contengan solo espacios en blanco.',
    parameter_invalid_string_empty: 'Uno o más valores de cadena obligatorios están vacíos. Asegúrese de que los valores de cadena contengan al menos un carácter.',
    parameter_missing: 'Faltan uno o más valores obligatorios. Consulte nuestra documentación de API para ver qué valores son necesarios para crear o modificar el recurso especificado.',
    parameter_unknown: 'La solicitud contiene uno o más parámetros inesperados. Elimínelos y vuelva a intentarlo.',
    parameters_exclusive: 'Se proporcionaron dos o más parámetros mutuamente excluyentes. Consulte la documentación de nuestra API o el mensaje de error devuelto para ver qué valores están permitidos al crear o modificar el recurso especificado.',
    payment_intent_action_required: 'El método de pago proporcionado requiere que el cliente complete las acciones, pero se configuró error_on_requires_action. Si desea agregar este método de pago a su integración, le recomendamos que primero actualice su integración para manejar las acciones.',
    payment_intent_authentication_failure: 'El método de pago proporcionado ha fallado la autenticación. Proporcione un nuevo método de pago para intentar cumplir este PaymentIntent nuevamente.',
    payment_intent_incompatible_payment_method: 'PaymentIntent esperaba un método de pago con propiedades diferentes a las proporcionadas.',
    payment_intent_invalid_parameter: 'Uno o más parámetros proporcionados no se permitieron para la operación dada en PaymentIntent. Consulte nuestra referencia de API o el mensaje de error devuelto para ver qué valores no eran correctos para ese PaymentIntent.',
    payment_intent_mandate_invalid: 'El mandato proporcionado no es válido y no se puede utilizar para la intención de pago.',
    payment_intent_payment_attempt_expired: 'El último intento de pago de PaymentIntent ha caducado. Consulte la propiedad last_payment_error en PaymentIntent para obtener más detalles y proporcione un nuevo método de pago para intentar cumplir este PaymentIntent nuevamente.',
    payment_intent_payment_attempt_failed: 'El último intento de pago de PaymentIntent ha fallado. Consulte la propiedad last_payment_error en PaymentIntent para obtener más detalles y proporcione un nuevo método de pago para intentar cumplir este PaymentIntent nuevamente.',
    payment_intent_unexpected_state: 'El estado de PaymentIntent era incompatible con la operación que intentaba realizar.',
    payment_method_bank_account_already_verified: 'Esta cuenta bancaria ya ha sido verificada.',
    payment_method_bank_account_blocked: 'Esta cuenta bancaria falló en la verificación en el pasado y no se puede usar. Contáctenos si desea intentar utilizar estas credenciales de cuenta bancaria.',
    payment_method_currency_mismatch: 'La moneda especificada no coincide con la moneda del método de pago adjunto. Solo se puede crear un pago para la misma moneda que el método de pago correspondiente.',
    payment_method_invalid_parameter: 'Se proporcionó un parámetro no válido en el objeto de método de pago. Consulte nuestra documentación de API o el mensaje de error devuelto para obtener más contexto.',
    payment_method_microdeposit_failed: 'No se pudieron depositar los microdepósitos en la cuenta bancaria del cliente. Verifique los números de cuenta, institución y tránsito, así como el tipo de moneda.',
    payment_method_microdeposit_verification_amounts_invalid:  'You must provide exactly two microdeposit amounts.',
    payment_method_microdeposit_verification_amounts_mismatch: 'Los montos proporcionados no coinciden con los montos que se enviaron a la cuenta bancaria.',
    payment_method_microdeposit_verification_attempts_exceeded: 'Has superado el número de intentos de verificación permitidos.',
    payment_method_microdeposit_verification_timeout: 'El método de pago debe ser verificado con microdepósitos dentro del período requerido.',
    payment_method_provider_decline: 'El pago fue rechazado por el emisor o el cliente. Consulte la propiedad last_payment_error en PaymentIntent para obtener más detalles y proporcione un nuevo método de pago para intentar cumplir este PaymentIntent nuevamente.',
    payment_method_provider_timeout: 'El método de pago falló debido a un tiempo de espera. Consulte la propiedad last_payment_error en PaymentIntent para obtener más detalles y proporcione un nuevo método de pago para intentar cumplir este PaymentIntent nuevamente.',
    payment_method_unactivated: 'La operación no se puede realizar porque el método de pago utilizado no ha sido activado. Active el método de pago en el Panel de control y vuelva a intentarlo.',
    payment_method_unexpected_state: 'El estado del método de pago proporcionado no era compatible con la operación que intentaba realizar. Confirme que el método de pago esté en un estado permitido para la operación dada antes de intentar realizarla.',
    payment_method_unsupported_type: 'La API solo admite métodos de pago de ciertos tipos.',
    payouts_not_allowed: 'Los pagos se han desactivado en la cuenta conectada. Verifique el estado de la cuenta conectada para ver si es necesario proporcionar información adicional o si los pagos se han inhabilitado por otro motivo.',
    platform_account_required: 'Solo las plataformas Stripe Connect pueden funcionar con otras cuentas. Si necesita configurar una plataforma Stripe Connect, puede hacerlo en el panel de control.',
    platform_api_key_expired: 'La clave API proporcionada por su plataforma Connect ha caducado. Esto ocurre si su plataforma ha generado una nueva clave o la cuenta conectada se ha desconectado de la plataforma. Obtenga sus claves API actuales del Panel y actualice su integración, o comuníquese con el usuario y vuelva a conectar la cuenta.',
    postal_code_invalid: 'El código postal proporcionado es incorrecto.',
    processing_error: 'Ocurrió un error al procesar la tarjeta. Vuelve a intentarlo más tarde o con otro método de pago.',
    product_inactive: 'El producto al que pertenece este SKU ya no está disponible para su compra.',
    rate_limit: 'Demasiadas solicitudes llegan a la API demasiado rápido. Recomendamos una retirada exponencial de sus solicitudes.',
    resource_already_exists: 'Ya existe un recurso con un ID especificado por el usuario (p. Ej., Plan o cupón). Utilice un valor diferente y único para id e inténtelo de nuevo.',
    resource_missing: 'La identificación proporcionada no es válida. El recurso no existe o se ha proporcionado un ID para un recurso diferente.',
    routing_number_invalid: 'El número de ruta bancaria proporcionado no es válido.',
    secret_key_required: 'La clave API proporcionada es una clave publicable, pero se requiere una clave secreta. Obtenga sus claves API actuales del Panel y actualice su integración para usarlas.',
    sepa_unsupported_account: 'Su cuenta no admite pagos SEPA.',
    setup_attempt_failed: 'El último intento de instalación de SetupIntent ha fallado. Consulte la propiedad last_setup_error en SetupIntent para obtener más detalles y proporcione un nuevo método de pago para intentar configurarlo nuevamente.',
    setup_intent_authentication_failure: 'El método de pago proporcionado ha fallado la autenticación. Proporcione un nuevo método de pago para intentar cumplir con este SetupIntent nuevamente.',
    setup_intent_invalid_parameter: 'Uno o más parámetros proporcionados no se permitieron para la operación dada en SetupIntent. Consulte nuestra referencia de API o el mensaje de error devuelto para ver qué valores no eran correctos para ese SetupIntent.',
    setup_intent_unexpected_state: 'El estado de SetupIntent era incompatible con la operación que intentaba realizar.',
    shipping_calculation_failed: 'El cálculo del envío falló porque la información proporcionada era incorrecta o no se pudo verificar.',
    sku_inactive: 'El SKU está inactivo y ya no está disponible para su compra. Utilice un SKU diferente o active el SKU actual nuevamente.',
    state_unsupported: 'Se produce cuando se proporciona la información legal_entity para una cuenta personalizada de EE. UU., Si el estado proporcionado no es compatible. (Se trata principalmente de estados y territorios asociados).',
    tax_id_invalid: 'El número de identificación fiscal proporcionado no es válido (por ejemplo, faltan dígitos). La información de identificación fiscal varía de un país a otro, pero debe tener al menos nueve dígitos.',
    taxes_calculation_failed: 'Error en el cálculo de impuestos para el pedido.',
    terminal_location_country_unsupported: 'Actualmente, la terminal solo está disponible en algunos países. No se pueden crear ubicaciones en su país en modo en vivo.',
    testmode_charges_only: 'Su cuenta no ha sido activada y solo puede realizar cargos de prueba. Active su cuenta en el Panel de control para comenzar a procesar los cargos reales.',
    tls_version_unsupported: 'Su integración utiliza una versión anterior de TLS que no es compatible. Debe utilizar TLS 1.2 o superior.',
    token_already_used: 'El token proporcionado ya se ha utilizado. Debes crear un nuevo token antes de poder volver a intentar esta solicitud.',
    token_in_use: 'El token proporcionado se está utilizando actualmente en otra solicitud. Esto ocurre si su integración realiza solicitudes duplicadas simultáneamente.',
    transfers_not_allowed: 'No se puede crear la transferencia solicitada. Contáctenos si recibe este error.',
    upstream_order_creation_failed: 'No se pudo crear el pedido. Verifique los detalles del pedido y vuelva a intentarlo.',
    url_invalid: 'La URL proporcionada no es válida.'
}

module.exports = erroresStripe;